#!/usr/bin/env bash
# scripts/signals/collect.sh
#
# Pull every public adoption signal for eunox into a single Markdown
# report. Designed to run on a weekly cron from
# .github/workflows/adoption-signals.yml, but also runs locally for ad-hoc
# snapshots.
#
# No client-side telemetry is involved. Every signal below is data the
# public can already read from a public API — this script is just an
# aggregator. The eunox proxy itself makes no network calls except those
# the manifest authorizes.
#
# Requirements: gh (authenticated), jq, curl. On GitHub Actions the
# default GITHUB_TOKEN is sufficient for most calls; the Traffic API
# requires push access, so locally run with `gh auth login` against an
# account that has it. Calls that 403 degrade to zero so the rest of
# the report still renders.

set -euo pipefail

REPO="${REPO:-eunolabs/eunox}"
NOW="$(date -u +%Y-%m-%d)"
WEEK_AGO="$(date -u -d '7 days ago' +%Y-%m-%dT%H:%M:%SZ 2>/dev/null \
            || date -u -v-7d +%Y-%m-%dT%H:%M:%SZ)"

# --- helpers -----------------------------------------------------------

# API call that returns "{}" on any non-2xx so jq downstream still works.
api() {
  gh api "$@" 2>/dev/null || echo '{}'
}

# Count results in a search API call, returning 0 if the query was
# rate-limited / unauthorized.
search_count() {
  local q="$1"
  gh api -X GET "search/code" -f q="$q" 2>/dev/null \
    | jq -r '.total_count // 0' \
    || echo 0
}

# --- header ------------------------------------------------------------

cat <<EOF
# Adoption signals — $NOW

> Generated by \`scripts/signals/collect.sh\`. Every metric below is
> derived from a public API — no client-side telemetry exists. See
> [scripts/signals/README.md](README.md) for what each number means
> and how to interpret it.
>
> Repo: \`$REPO\`.

EOF

# --- 1. Repository -----------------------------------------------------

cat <<'EOF'
## 1. Repository

EOF

repo_json="$(api "repos/$REPO")"
jq -r '
  "| Metric | Value |",
  "|---|---|",
  "| Stars            | \(.stargazers_count   // 0) |",
  "| Forks            | \(.forks_count        // 0) |",
  "| Watchers         | \(.subscribers_count  // 0) |",
  "| Open issues + PRs| \(.open_issues_count  // 0) |"
' <<<"$repo_json"
echo

# --- 2. Traffic (14d rolling) ------------------------------------------

cat <<'EOF'
## 2. Traffic — 14-day rolling

EOF

views="$(api "repos/$REPO/traffic/views")"
clones="$(api "repos/$REPO/traffic/clones")"

cat <<EOF
| Signal | Total | Unique |
|---|---|---|
| Views  | $(jq -r '.count   // 0' <<<"$views") | $(jq -r '.uniques // 0' <<<"$views") |
| Clones | $(jq -r '.count   // 0' <<<"$clones") | $(jq -r '.uniques // 0' <<<"$clones") |

EOF

# Top referrers + paths, if any.
referrers="$(api "repos/$REPO/traffic/popular/referrers")"
if [[ "$(jq 'if type=="array" then length else 0 end' <<<"$referrers")" -gt 0 ]]; then
  echo "### Top referrers"
  echo
  echo "| Source | Views | Unique |"
  echo "|---|---|---|"
  jq -r '.[] | "| \(.referrer) | \(.count) | \(.uniques) |"' <<<"$referrers"
  echo
fi

paths="$(api "repos/$REPO/traffic/popular/paths")"
if [[ "$(jq 'if type=="array" then length else 0 end' <<<"$paths")" -gt 0 ]]; then
  echo "### Top paths"
  echo
  echo "| Path | Views | Unique |"
  echo "|---|---|---|"
  jq -r '.[] | "| `\(.path)` | \(.count) | \(.uniques) |"' <<<"$paths"
  echo
fi

# --- 3. Releases -------------------------------------------------------

cat <<'EOF'
## 3. Releases — downloads + verification

Binary downloads are the closest proxy to active installs. The
`checksums.txt.sigstore.json` count is the number of people who actually
verified the supply chain — a uniquely interesting signal for a security
product. SBOM downloads are users plugging into SCA tooling.

EOF

# --paginate emits one JSON array per page; --slurp wraps those pages into an
# array-of-arrays which `jq add` flattens into a single array, so the downstream
# `length` / row rendering see exactly one array even past the first page.
releases="$(gh api "repos/$REPO/releases" --paginate --slurp 2>/dev/null \
            | jq 'add // []' 2>/dev/null || echo '[]')"

if [[ "$(jq 'length' <<<"$releases")" -eq 0 ]]; then
  echo "_No releases yet — open the first issue if this is wrong after \`v0.1.0\`._"
  echo
else
  echo "| Tag | Binaries | checksums.txt.sigstore.json | SBOMs | Published |"
  echo "|---|---|---|---|---|"
  jq -r '
    .[] |
    ([ .assets[] |
       select(.name | test("\\.(sig|pem|sigstore\\.json|sbom\\.json|txt)$") | not) |
       .download_count ] | add // 0) as $bins |
    ([ .assets[] |
       select(.name == "checksums.txt.sigstore.json") |
       .download_count ] | add // 0) as $sigs |
    ([ .assets[] |
       select(.name | test("\\.sbom\\.json$")) |
       .download_count ] | add // 0) as $sboms |
    "| \(.tag_name) | \($bins) | \($sigs) | \($sboms) | \(.published_at[:10]) |"
  ' <<<"$releases"
  echo
fi

# --- 4. Issues + PRs in last 7d ----------------------------------------

cat <<EOF
## 4. Activity — last 7 days (since $WEEK_AGO)

EOF

# Issues endpoint returns both issues and PRs; we split them.
recent="$(gh api "repos/$REPO/issues" -X GET \
            -f state=all -f since="$WEEK_AGO" -f per_page=100 --paginate \
            2>/dev/null | jq -s 'flatten' || echo '[]')"

total="$(jq 'length' <<<"$recent")"
prs="$(jq '[.[] | select(.pull_request)] | length' <<<"$recent")"
issues_only=$((total - prs))
authors="$(jq -r '[.[].user.login] | unique | length' <<<"$recent")"

cat <<EOF
| Metric | Count |
|---|---|
| New / updated issues | $issues_only |
| New / updated PRs    | $prs |
| Distinct authors     | $authors |

EOF

# Author breakdown so you can eyeball who's filing.
if [[ "$total" -gt 0 ]]; then
  echo "### Authors this week"
  echo
  jq -r '
    [.[].user.login] | group_by(.) |
    map({login: .[0], count: length}) |
    sort_by(-.count) | .[] |
    "- @\(.login) — \(.count)"
  ' <<<"$recent"
  echo
fi

# --- 5. Public adoption — manifests in the wild ------------------------

cat <<'EOF'
## 5. Public adoption — manifests in the wild

The highest-signal indicator we have: people who write a real
manifest and commit it to a public repo. Counts are best-effort code
search; rate limits and Search-API indexing lag make these noisy.

EOF

# Each query excludes the source repo so we only count external use.
mentions="$(search_count 'eunox -repo:eunolabs/eunox language:YAML')"
shape="$(search_count   '"schemaVersion: 0.1" "capabilities:" -repo:eunolabs/eunox language:YAML')"
docker="$(search_count  'ghcr.io/eunolabs/eunox -repo:eunolabs/eunox')"
brew="$(search_count    'eunolabs/tap/eunox -repo:eunolabs/eunox')"

cat <<EOF
| Search | Hits |
|---|---|
| Public YAML files mentioning \`eunox\` | $mentions |
| Public YAML files matching the manifest shape | $shape |
| Public files referencing the Docker image | $docker |
| Public files referencing the Homebrew tap | $brew |

EOF

# --- 6. Fork lineage ---------------------------------------------------

cat <<'EOF'
## 6. Forks

Corp orgs forking is the design-partner pipeline. Personal-account
forks are largely "stash for later" — still worth knowing, but the
signal is the orgs.

EOF

# --slurp + `jq add` flattens the per-page arrays into one array (see the
# releases section above); without it a multi-page result feeds several lengths
# into the `[[ ... -eq 0 ]]` check and Bash rejects it as a syntax error.
forks_json="$(gh api "repos/$REPO/forks" --paginate --slurp 2>/dev/null \
              | jq 'add // []' 2>/dev/null || echo '[]')"

if [[ "$(jq 'length' <<<"$forks_json")" -eq 0 ]]; then
  echo "_No forks yet._"
else
  echo "| Owner | Type | Pushed |"
  echo "|---|---|---|"
  jq -r '
    .[] |
    "| \(.owner.login) | \(.owner.type) | \(.pushed_at[:10]) |"
  ' <<<"$forks_json"
fi
echo

# --- 7. Known gaps -----------------------------------------------------

cat <<'EOF'
## 7. Known gaps

These signals would be valuable but we don't have a programmatic source
yet — check them manually if you want a full picture:

- **ghcr.io pull counts** — not exposed by the Packages API. Visible in
  the GitHub UI at `github.com/orgs/eunolabs/packages/container/eunox`.
- **Homebrew install analytics** — `formulae.brew.sh` only publishes
  analytics for the core taps. Third-party tap installs are aggregated
  but not published.
- **Registry counters** — mcp.so, Smithery, Cline marketplace each show
  per-listing stats in their own UI; no scraping wired up yet.
- **Press / social** — HN, Lobsters, dev.to comment counts. Track
  qualitatively.
EOF
