# Copyright 2026 Eunolabs, LLC
# SPDX-License-Identifier: Apache-2.0

name: OpenSSF Scorecard

on:
  push:
    branches: [main]
  branch_protection_rule:
  schedule:
    - cron: "43 8 * * 1"
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  scorecard:
    name: Scorecard
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      id-token: write
      security-events: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Run OpenSSF Scorecard
        uses: ossf/scorecard-action@f49aabe0b5af0936a0987cfb85d86b75731b0186 # v2.4.1
        with:
          results_file: scorecard.sarif
          results_format: sarif
          publish_results: true

      - name: Upload Scorecard SARIF
        uses: github/codeql-action/upload-sarif@99df26d4f13ea111d4ec1a7dddef6063f76b97e9 # v4
        with:
          sarif_file: scorecard.sarif
